include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
    
  exclude:
    - build/**
    - .dart_tool/**
    - ios/Pods/**
    - ios/build/**
    - android/.gradle/**
    - android/build/**
    - windows/flutter/ephemeral/**
    - .pub-cache/**

linter:
  rules:
    prefer_single_quotes: true
    unnecessary_const: true
    unnecessary_new: true
    avoid_print: true